### PR TITLE
Publish docker images on dockerhub

### PR DESCRIPTION
**Pull request by godu**
On each tag push, Travis will build and publish 2 images
- `ifsharp/ifsharp:latest`
- `ifsharp/ifsharp:<tag>` 

## Demo

If create new tag on my fork https://github.com/godu/IfSharp/releases/tag/v3.0.1
Travis build : https://travis-ci.com/godu/IfSharp/builds/80667557
DockerHub tags : https://hub.docker.com/r/godu/ifsharp/tags/

## Next
- [x] Create docker account `fsprojects`
- [x] Adds DOCKER_USERNAME DOCKER_PASSWORD on travis
- [ ] Publish a new tag, wait and see

### CODE REVIEW

**Comment by cgravill** [comment]
Looks like a nice improvement to have an automated deployment.

In terms of the username and password, any suggestions how this would be managed? Do you know if other docker images are automatically published and how they handle accounts like this?

**Comment by godu** [comment]
@cgravill In my company, we build images for every commit and publish it to docker registry.
Cf https://hub.docker.com/u/coorpacademy/
I have some knowledge about DockerHub, and this is my following advice :

Docker doesn't provide access token system like [github](https://github.com/settings/tokens). I think [travis are right](https://docs.travis-ci.com/user/docker/#branch-based-registry-pushes), we have to use username/password as credentials.

You should : 
- [ ] create a [ifsharp organization](https://hub.docker.com/organizations/add/)
- [ ] create a [ifsharp repository](https://hub.docker.com/add/repository/?namespace=ifsharp) 
- [ ] set your own username/password as env variables [in travis](https://travis-ci.org/fsprojects/IfSharp/settings) to push images.

**Comment by cgravill** [comment]
OK, this seems better done at the fsprojects level as we don't want single points of failure. Can we join with whatever is happening here: https://hub.docker.com/_/fsharp/ ?

**Comment by dsyme** [comment]
Hi all,

@gbaydin and I are diving into iFSharp and we've realised that we will need dockerhub images for iFSharp.  

I've created a community organization on docker cloud https://cloud.docker.com/u/fsprojects/ which we can use for all "fsprojects"  projects.

@baronfel - If you'd like to be co-admin on that please send me your dockerhub ID.

@cgravill - Could you confirm your dockerhub ID is "cgravill"?  

thanks
don

**Comment by cgravill** [comment]
Hi @dsyme yes that's me and I've had a notification from docker hub.

**Comment by dsyme** [comment]
@godu @cgravill We'll look at updating this PR and getting this in, if that's ok

**Comment by cgravill** [comment]
Sure, would you like me to resolve the conflicts? I know what's going on with them - enabling the experimental .NET Core builds, and reordering the readme.

**Comment by baronfel** [comment]
Excellent news, and of course I'll help. My docker hub ID is chusk3@gmail.com.

**Comment by dsyme** [comment]
> Sure, would you like me to resolve the conflicts? I know what's going on with them - enabling the experimental .NET Core builds, and reordering the readme.

Yes please! thanks!

**Comment by cgravill** [comment]
Done! I haven't checked the local Docker instructions still work. Note to other that this Docker build is targeting the stable Mono version of this.

Getting to .NET Core on Docker in the future would be great.

**Comment by dsyme** [comment]
> Getting to .NET Core on Docker in the future would be great.



I'll look at this too

**Comment by dsyme** [comment]
OK, so we've 

* [x] updated this with what we think is necessary to push docker images automatically (on all tags)
* [x] added encrypted the username and password to push to [fsprojects/ifsharp docker hub](https://cloud.docker.com/u/fsprojects/repository/registry-1.docker.io/fsprojects/ifsharp) 
* [x] pushed experimental tag `v3.0.0-beta3docker`

This is now building at https://travis-ci.org/fsprojects/IfSharp/builds/511585157 and all

**Comment by cgravill** [comment]
That's great and it looks like the .NET Core SDK is now working correctly on Travis too!

**Comment by dsyme** [comment]
All working, images here https://cloud.docker.com/u/fsprojects/repository/registry-1.docker.io/fsprojects/ifsharp

**Pull request merged**
