### PR TITLE
Enable use of Xplot.Plotly in experimental .NET Core version

### PR DESCRIPTION
**Pull request by cgravill**
Adjust copying of paket.dependencies to drop /hide directory (needed to avoid dev vs deploy split)
Output all files from dependencies (via CopyLocalLockFileAssemblies) - easier debugging
Include new XPlot.Plotly library, get with storage:none

### CODE REVIEW

**Comment by cgravill** [comment]
Screenshot on Windows:
image

(the error highlighted is benign, as yet unresolved code completion issue with netstandard)

**Comment by cgravill** [comment]
Works on macOS as well:

Screen Shot 2019-05-06 at 14 08 46

**Comment by cgravill** [comment]
Included in this also makes the helper scripts for Paket work with .NET Core. I've not widely tested this but it's much further along.

The way I've implemented this and configured Paket means it uses the storage:none experiment helps with #112

**Comment by cgravill** [comment]
There's a build failure on Travis that seems unrelated to these changes:  

```
Removing intermediate container c92a19c3b84a
 ---> 782e3ef391de
Step 9/34 : RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
 ---> Running in 3a6302d2480e
Removing intermediate container 3a6302d2480e
 ---> 1d155d6b4980
Step 10/34 : RUN mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
 ---> Running in 0f6a3af75cd6
Removing intermediate container 0f6a3af75cd6
 ---> 0bc76fd9a59e
Step 11/34 : RUN wget -q https://packages.microsoft.com/config/debian/9/prod.list
 ---> Running in 329b85947c67
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

I'm going to go ahead an merge but it might need independent follow-up. @dsyme you were improving the Docker builds, are these steps just slow? Perhaps we need to adjust https://stackoverflow.com/a/32750561/35544 or alternatively the Azure DevOps builds seem much faster than Travis, perhaps we can move?

**Comment by cgravill** [comment]
btw much appreciated @jackfoxy the recent support you added to https://github.com/fslaborg/XPlot for netstandard2.0 making this much easier and clean!

**Comment by jackfoxy** [comment]
@cgravill  thanks for the positive feedback

**Pull request merged**
