### PR TITLE
Remove dependency to System.Drawing (which helps when running on *nix)

### PR DESCRIPTION
**Pull request by smoothdeveloper**
I'm sorry as I couldn't test this change as I don't have all prerequesites installed on my machine.

Please let me know if you see any issue or want me to make adjustments.

#133

### CODE REVIEW

**Comment by cgravill** [comment]
I'd be very happy to minimise or remove our dependency on System.Drawing. We've been moving to less compulsory references e.g. charting libraries which required System.Drawing. This makes everything more flexible for Windows users too.

There's also no particular reason we need to turn the resources into images just to save them out either!

It's a possible breaking change to remove a reference so we'll need to test. I've just checked https://fslab.org/FSharp.Charting/ on Windows with your branch and it was still able to plot server-side so that looks good. We'd need someone to check this on both Linux and macOS. I've just sent you a pull request fixing a very minor issue the Travis CI build showed under Mono.

**Comment by cgravill** [comment]
Tested on a full Mono and Anaconda install on macOS and it works for me (as before). Ideally we should also test on the minimal install.

Could either @npmurphy or @sylvanc give Linux and this branch try if you get a chance please? Basically to ensure any plotting that used to work, still works.

**Comment by tautologico** [comment]
Everything working here: OS X El Capitan, installed mono and python3 (both from homebrew). At least for the example notebook it's all fine.

**Comment by npmurphy** [comment]
This PR seems to be working on Linux/Mono 4.8 beta (4.8.0.483/ba7f169).

**Comment by cgravill** [comment]
Excellent, thanks both for testing. Merging now.

**Pull request merged**
