### PR TITLE
Async display support & examples

### PR DESCRIPTION
**Pull request by dgrechka**
The PR adds an ability to asynchronously compute and display Async<_> results. An example of the usage is also included.

See the [demo notebook](https://nbviewer.jupyter.org/github/dgrechka/ifsharp/blob/async_display/FSharp_Jupyter_Notebooks.ipynb#Async-values-display).

Associated with #104.

### CODE REVIEW

**Comment by cgravill** [comment]
This looks excellent, there's a lot of core functionality adjusted. How widely have you tested it? Does it work with Mono?

**Comment by dgrechka** [comment]
Not yet.
I'll run it on Mono and will let you know how is it.

**Comment by dgrechka** [comment]
@cgravill I ran a bunch of examples on Mono.
The examples from introduction notebook work well. I think you are safe to merge.

**Comment by cgravill** [comment]
The new async functionality looks great and works for me as a second check.

There are a couple of new warnings:

```
Kernel.fs(309,13): warning FS0193: This expression is a function value, i.e. is missing arguments. Its type is (string * 'a) list -> 'b -> unit.
Kernel.fs(373,23): warning FS0067: This type test or downcast will always hold
```
the first could be problematic as it prevents the help instructions from displaying. Could you take a look please?

**Comment by dgrechka** [comment]
You are right! Thanks for spotting it!
Fixed now.

**Comment by cgravill** [comment]
Looks good, I'll merge now (the Travis failure is a network issue)

**Pull request merged**
