### PR TITLE
fcs 12.0.8

### PR DESCRIPTION
**Pull request by dsyme**

### CODE REVIEW

**Comment by dsyme** [comment]
cc @sylvanc @cgravill

**Comment by cgravill** [comment]
Should we be getting FSharp.Core.optdata FSharp.Core.sigdata out of \packages\FSharp.Core?

**Comment by dsyme** [comment]
> Should we be getting FSharp.Core.optdata FSharp.Core.sigdata out of \packages\FSharp.Core?

They are still in the package for old compiler versions consuming the package

**Comment by dsyme** [comment]
Have we seen this CI failure before?

```
C:\projects\ifsharp\tests\IfSharp.Kernel.Tests\startup(1,1): error FS1108: The type 'ITest' is required here and is unavailable. You must add a reference to assembly 'xunit.abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'. [C:\projects\ifsharp\tests\IfSharp.Kernel.Tests\IfSharp.Kernel.Tests.fsproj]
```

**Comment by sylvanc** [comment]
I can't seem to replicate that CI failure locally. We haven't seen it before.

**Comment by sylvanc** [comment]
Even after a nuget cache flush, this PR builds and runs fine for me (including being able to load packages in notebooks using paket).

Does anyone have the permissions needed to rerun the CI job? If not, @dsyme can you make a meaningless change to kick CI off again? I'm wondering if there was an intermittent problem.

**Comment by cgravill** [comment]
I haven't seen that failure before. It reproduces locally for me and I'm investigating it now.

Just triggered a new build.

**Comment by dsyme** [comment]
@cgravill @sylvanc I just reduced the PR to just be for FCS without the update to xunit 2.2

**Comment by sylvanc** [comment]
The xunit 2.1 PR also builds and runs fine for me.

**Comment by sylvanc** [comment]
And passes CI :) Merging now.

**Comment by cgravill** [comment]
Sounds good, we didn't need to upgrade to xunit 2.2 now. I'll look into that separately.

**Pull request merged**
