### PR TITLE
Added reference Microsoft.NETCore.App version 2.2.3

### PR DESCRIPTION
**Pull request by rudihorn**
This PR addresses issue #206.

### CODE REVIEW

**Comment by cgravill** [comment]
We mostly manage references using Paket at the moment. Is it possible to use Paket for this override as well?

**Comment by rudihorn** [comment]
I'll try to sort this out when I have some time

**Comment by cgravill** [comment]
I took at look into this and there's a suggestion we should use e.g.

```xml
<RuntimeFrameworkVersion>2.2.3</RuntimeFrameworkVersion>
```

https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#recommendations

rather than directly referencing a (meta)package directly.

This might limit portability a bit. @dsyme you had an overlapping change in #209 any clarity you can provide on the right way to approach this?

**Comment by dsyme** [comment]
I'll definitely be taking a look at this.  Constraining to a runtime version should not be needed for using TPs, so there is definitely something odd going on.

**Comment by rudihorn** [comment]
So I have a commit for the change as requested by @cgravill.

Admittedly @dsyme I haven't gone very in-depth into this problem, as to do that I would need to debug the FSharp.Compiler.Services library which was throwing somewhat unhelpful error messages. I did try to poke around in the code, but this wasn't straightforward enough without debugging.

**Comment by cgravill** [comment]
Thanks @rudihorn this avoids a warning too. In principal, I'm happy to merge this.

@dsyme it sounds like you're going to try to get to the bottom of this which would be even better.

**Comment by rudihorn** [comment]
Hmm for some reason I am unable to reproduce the error today and it seems to be working with just the `Microsoft.NETCore.App=2.2.0` runtime reference. I'm wondering if this was me just thinking that the intellisense warning was not causing the command to be issued.

**Comment by rudihorn** [comment]
Yes I think it was just me just having a long day and seeing a red squiggly line with no output. I'll close this PR for now as I don't think it actually solves any issue.

**Comment by cgravill** [comment]
OK no problem, there are definitely things that need fixing with the .NET Core support even if this isn't quite the one.

**Pull request closed without merging**
